### ISSUE TITLE
Issues with Part 1, Page 66

### ISSUE THREAD

**Issue by starkraven** [chaupt/ruby-for-kids-projects#2]
I can't get the word HELLO to appear horizontal. Is there a mistake in the book?

**Comment by chaupt** [comment]
@starkraven I completely missed seeing this for so long. Hope you figured it out, but if not, let me know if you might still want some help or if you tried the version checked in here. I'm using the project with some classes I'm teaching now and there could be a typo. If you paste your code in to the issue and tag me (use @chaupt), I'll see it immediately. My sincere apology for an email fail on my part!

If the individual letters were displaying as expected try copy and pasting this:

```
0.upto(6) do |count|
  puts "#{h[count]} #{e[count]} #{l[count]} #{l[count]} #{o[count]}"
end
```
